maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path('', views.simplemap),
    path('co-ban/', views.simplemap, name="co-ban"),
    path('tim-kiem/', views.search, name="tim-kiem"),
    path('cinema/', views.cinema, name="cinema"),
    path('api/geojson/cinema/', views.cinema_geojson, name='rap_data'),

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.post_page, name='post_page'),
]

viet/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.aboutpage),
    path('posts/', include('posts.urls')),
    path('maps/', include('maps.urls')),
]

maps/models.py
from django.db import models

class RapChieuPhim(models.Model):
    ten_rap = models.CharField(max_length=255)
    dia_chi = models.TextField()
    kinh_do = models.FloatField()  # longitude
    vi_do = models.FloatField()    # latitude
    mo_ta = models.TextField(blank=True, null=True)
    anh_rap = models.ImageField(upload_to='cinema/', null=True, blank=True)  # Thêm cột hình ảnh

    def __str__(self):
        return self.ten_rap

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

maps/views.py
from django.shortcuts import render
from .models import RapChieuPhim
from django.http import JsonResponse

# Create your views here.
def simplemap(request):
    return render(request, 'simple-map.html')
def search(request):
    return render(request, 'search-address.html')
def cinema(request):
    return render(request, 'index.html')
def cinema_geojson(request):
    features = []

    for rap in RapChieuPhim.objects.all():
        features.append({
            "type": "Feature",
            "properties": {
                "name": rap.ten_rap,
                "address": rap.dia_chi,
                "description": rap.mo_ta
            },
            "geometry": {
                "type": "Point",
                "coordinates": [rap.kinh_do, rap.vi_do]  # lon, lat
            }
        })

    data = {
        "type": "FeatureCollection",
        "features": features
    }

    return JsonResponse(data)

posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.http import HttpResponse

# Create your views here.
def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/post_list.html', {'posts': posts})
# def post_page(request, slug):
#     return HttpResponse(slug)
def post_page(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'posts/post_detail.html', {'post': post})

viet/views.py
#from django.http import HttpResponse
from django.shortcuts import render
def homepage(request):
    #return HttpResponse("Xin chao Django")
    return render(request, 'home.html')

def aboutpage(request):
    #return HttpResponse("Day la trang gioi thieu")
    return render(request, 'about.html')

maps/templates/index.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Map Page
{% endblock %}

{% block map %}
  <link rel="stylesheet" href="{% static 'css/map/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/cinema/style.css' %}" />
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
  <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
  <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
  <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.js"></script>
{% endblock %}

{% block content %}
  <!-- Sidebar bên phải -->

  <div class="container-fluid">
    <div class="row" style="height: 650px">
      <div id="map">
        <div id="sidebar" class="sidebar">
          <div class="sidebar-content">
            <!-- Nội dung sẽ được thêm bằng JavaScript -->
          </div>
          <button class="close-btn" onclick="closeSidebar()">✖</button>
        </div>
      </div>
    </div>
    <ul class="layers"></ul>
  </div>
{% endblock %}

{% block script %}
  <script src="{% static 'js/cinema/map-config.js' %}"></script>
  <script src="{% static 'js/cinema/layer-control.js' %}"></script>
  <script src="{% static 'js/cinema/routing.js' %}"></script>
  <script src="{% static 'js/cinema/script.js' %}"></script>
{% endblock %}

maps/templates/search-address.html
{% extends 'layout.html' %} {% load static %} {% block title %}
  Tìm kiếm địa vào địa chỉ
{% endblock %} {% block map %}
  <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
  <link rel="stylesheet" href="{% static 'css/map/map.css' %}" />
  <script src="{% static 'leaflet/leaflet.js' %}"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/tomickigrzegorz/autocomplete@1.8.6/dist/css/autocomplete.min.css" />
  <script src="https://cdn.jsdelivr.net/gh/tomickigrzegorz/autocomplete@1.8.6/dist/js/autocomplete.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.js"></script>
{% endblock %}
<style>
  .description {
    width: 300px;
    font-size: 16px;
    color: #333;
    padding: 10px 14px;
    background-color: hsla(0, 0%, 100%, 0.8);
    box-shadow: 0 0 15px rgb(0 0 0 / 20%);
    border-radius: 5px;
    line-height: 120%;
    border: 1px solid grey;
  }
</style>

{% block content %}
  <section class="special-services">
    <div class="container mb-3">
      <div class="auto-search-wrapper loupe text-center">
        <input type="text" autocomplete="off" id="search" placeholder="Nhập vào tên thành phố" />
      </div>
    </div>

    <div class="container-fluid">
      <div class="row" style="height: 800px">
        <div id="map"></div>
      </div>
    </div>
  </section>
{% endblock %} {% block script %}
  <script src="{% static 'js/map/search-address.js' %}"></script>
{% endblock %}

maps/templates/simple-map.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Bản đồ cơ bản
{% endblock %}

{% block map %}
  <link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}" />
  <link rel="stylesheet" href="{% static 'css/map/map.css' %}" />
  <script src="{% static 'leaflet/leaflet.js' %}"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.6.0/Control.FullScreen.min.js"></script>
{% endblock %}

{% block content %}
  <section class="special-services">
    <div class="container-fluid">
      <div class="section-title text-center" data-aos="fade-up">
        <h2>Bản đồ cơ bản</h2>
      </div>
      <div class="marker-position"></div>
      <div class="row" style="height: 800px;">
        <div id="map"></div>
      </div>
      <div class="services_mask">
        <img src="{% static 'assets/img/mask09.svg' %}" alt="Icon" class="img-fluid mask_01" />
      </div>
    </div>
  </section>
{% endblock %}

{% block script %}
  <script src="{% static 'js/map/simple.js' %}"></script>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "layout.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
        <h1>{{ post.title }}</h1>
        <p><em>Ngày đăng: {{ post.date }}</em></p>
        <p>{{ post.body|linebreaks }}</p> 
        <br>
        <a href="{% url 'post:post_list' %}">⬅ Quay lại danh sách bài viết</a>
    </section>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'layout.html' %}

{% block title %}
  Danh sách bài viết
{% endblock %}

{% block content %}
  <section>
    <h1>Danh sách bài viết</h1>
    <ul>
      {% for post in posts %}
        <article class="post">
          <h2><a href="{% url 'post:post_page' slug=post.slug%}">{{post.title}}</a></h2>
          <p>{{ post.date }}</p>
          <p>{{ post.body }}</p>
        </article>
      {% endfor %}
    </ul>
    <p>
      Muốn quay trở lại <a href="/">trang chủ</a>
    </p>
  </section>
{% endblock %}

templates/about.html
{% extends "layout.html" %}

{% block title %}
    Giới thiệu
{% endblock %}

{% block content %}
    <h1>Trang Giới thiệu</h1>
    <p>Muốn quay trở lại<a href="/">trang chủ</a></p>
{% endblock %}

templates/footer.html
{% load static %}
<footer>
    <div class="footer-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-6 order-lg-0 order-4">
            <div class="footer-area-about mb-50" data-aos="fade-up">
              <h4>About Us</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut scelerisque arcu, at porttitor lacus. Integer.</p>
              <div class="footer-area-links">
                <a href="javascript:void(0)"><i class="fab fa-facebook-f"></i></a>
                <a href="javascript:void(0)"><i class="fab fa-twitter"></i></a>
                <a href="javascript:void(0)"><i class="fab fa-instagram"></i></a>
              </div>
            </div>
          </div>
          <div class="col-lg-2 mr-lg-65 col-md-4 col-6 order-lg-0 order-md-1">
            <div class="footer-area-lists mb-30" data-aos="fade-up" data-aos-delay="300">
              <h4>Company</h4>
              <ul>
                <li>
                  <a href="about-us.html">About us</a>
                </li>
                <li>
                  <a href="contact.html">Contact us</a>
                </li>
                <li>
                  <a href="javascript:void(0)">Careers</a>
                </li>
                <li>
                  <a href="javascript:void(0)">Press</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-2 mr-lg-65 col-md-4 col-6 order-lg-0 order-2">
            <div class="footer-area-lists mb-30" data-aos="fade-up" data-aos-delay="400">
              <h4>Products</h4>
              <ul>
                <li>
                  <a href="javascript:void(0)">Features</a>
                </li>
                <li>
                  <a href="javascript:void(0)">Pricing</a>
                </li>
                <li>
                  <a href="javascript:void(0)">News</a>
                </li>
                <li>
                  <a href="javascript:void(0)">Help desk</a>
                </li>
                <li>
                  <a href="contact.html">Support</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-2 col-md-4 col-6 order-lg-0 order-md-3">
            <div class="footer-area-lists" data-aos="fade-up" data-aos-delay="500">
              <h4>Legal</h4>
              <ul>
                <li>
                  <a href="javascript:void(0)">Privacy Policy</a>
                </li>
                <li>
                  <a href="javascript:void(0)">Terms & Conditions</a>
                </li>
                <li>
                  <a href="javascript:void(0)">Return Policy</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-area-shape">
        <img data-aos="fade-down" data-aos-easing="linear" data-aos-delay="600" src="{% static 'img/mask/penta-02.svg' %}" alt="shape" class="img-fluid ft-shape-01" />
        <img data-aos="fade-down" data-aos-easing="linear" data-aos-delay="700" src="{% static 'img/mask/downShape.svg' %}" alt="shape" class="img-fluid ft-shape-02" />
        <img data-aos="fade-left" data-aos-easing="linear" data-aos-delay="500" src="{% static 'img/mask/circle-01.svg' %}" alt="shape" class="img-fluid ft-shape-03" />
      </div>
    </div>
    <!-- copyright area -->
    <div class="copyright">
      <div class="container">
        <div class="row align-items-center copyright-area">
          <div class="col-lg-5 col-md-4 col-sm-12">
            <div class="copyright-area-text">
              <p>Copyright 2020. All Rights Reserved by us!</p>
            </div>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-12">
            <div class="copyright-area-logo">
              <a href="index.html"><img src="{% static 'img/logo/logo.png' %}" alt="logo" class="img-fluid" /></a>
            </div>
          </div>
          <div class="col-lg-5 col-md-4 col-sm-12">
            <div class="copyright-area-top text-lg-right">
              <a href="#header" id="to-top">Back to Top <i class="fas fa-angle-up"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/header.html
{% load static %}
<header id="header" class="header-area">
  <div class="container custom-container">
    <nav class="menu-area d-flex align-items-center">
      <div class="logo">
        <a href="index.html"><img src="{% static 'img/logo/logo.png' %}" alt="logo" /></a>
      </div>
      <ul class="main-menu d-flex align-items-center">
        <li>
          <a class="active" href="javascript:void(0)">Home</a>
          <ul class="sub-menu">
            <li>
              <a href="/">🏠</a>
            </li>
            <li>
              <a href="/about">❌</a>
            </li>
            <li>
              <a href="{% url 'post:post_list' %}">📋</a>
            </li>
            <li>
              <a href="home-4.html">Home Style 4</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:void(0)">Bản đồ</a>
          <ul class="sub-menu">
            <li>
              <a href="{% url 'maps:co-ban' %}">Cơ bản</a>
            </li>
            <li>
              <a href="{% url 'maps:tim-kiem' %}">Tim kiem</a>
            </li>
            <li>
              <a href="{% url 'maps:cinema' %}">Cinema</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:void(0)">About Us</a>
          <ul class="sub-menu">
            <li>
              <a href="about-us.html">About Us</a>
            </li>
            <li>
              <a href="team.html">Team Members</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:void(0)">Portfolio</a>
          <ul class="sub-menu">
            <li>
              <a href="project.html">Project</a>
            </li>
            <li>
              <a href="project-details.html">Project Detail</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:void(0)">Blog</a>
          <ul class="sub-menu">
            <li>
              <a href="blog.html">Blog</a>
            </li>
            <li>
              <a href="blog-details.html">Blog Details</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="contact.html">Contact Us</a>
        </li>
      </ul>
      <div class="right-content ml-auto">
        <div class="search-bar">
          <img src="{% static 'img/logo/search.svg' %}" alt="search logo" />
        </div>
        <div class="contact-number">
          <a class="primary__button primary__button-bgBlack" href="tel:+987 45478 547">
            <img src="{% static 'img/logo/phone-alt.svg' %}" alt="phone alt" />
            +987 45478 547
          </a>
        </div>
      </div>
      <div class="hamburger-menu">
        <span></span><span></span><span></span>
      </div>
    </nav>
    <aside>
      <div class="sidebar-menu">
        <div class="close-sidebar">
          <span></span><span></span>
        </div>
        <div class="logo">
          <a href="index.html"><img src="{% static 'img/logo/logo.png' %}" alt="logo" /></a>
        </div>
        <form class="asidesearch-bar">
          <input type="text" name="search" />
          <img src="{% static 'img/logo/search.svg' %}" alt="search logo" />
        </form>
        <ul class="main-menu">
          <li>
            <a class="active" href="index.html">Home</a>
          </li>
          <li>
            <a href="services.html">Services</a>
          </li>
          <li>
            <a href="about-us.html">About Us</a>
          </li>
          <li>
            <a href="project.html">Portfolio</a>
          </li>
          <li>
            <a href="blog.html">Blog</a>
          </li>
          <li>
            <a href="contact.html">Contact Us</a>
          </li>
        </ul>
        <a class="primary__button primary__button-bgBlack contacprimary__button" href="tel:+987 45478 547">
          <img src="{% static 'img/logo/phone-alt.svg' %}" alt="phone alt" />
          +987 45478 547
        </a>
      </div>
      <div class="overlay"></div>
    </aside>
  </div>
  <div class="search-box">
    <div class="search-form">
      <form action="#">
        <input type="text" placeholder="Enter Your Kayword" />
        <button type="submit"><img src="{% static 'img/logo/search.svg' %}" alt="search logo" /></button>
      </form>
    </div>
    <a class="search-close" href="javascript:void(0)"><i class="fas fa-times"></i></a>
  </div>
</header>

templates/home.html
{% extends "layout.html" %}

{% block title %}
    Trang chủ
{% endblock %}

{% block content %}
    <h1>Trang chủ</h1>
    <p>Để xem thêm chi tiết <a href="/about">tại đây</a> </p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon/boy.png' %}" />

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/slick.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/default.css' %}" />
    <link rel="stylesheet" href="{% static 'css/aos.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block map %}

    {% endblock %}
  </head>
  <body>
    {% include 'header.html' %}

    <main style="position: relative; min-height: 100%; height: 100%;">
      {% block content %}

      {% endblock %}
    </main>

    {% include 'footer.html' %}

    {% load static %}

    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/circle-progress.min.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/slider.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script>
      /* magnificPopup video view*/
      $('.popup-video').magnificPopup({
        type: 'iframe'
      })
    </script>
    {% block script %}

    {% endblock %}
    <!-- Purchase Button -->
  </body>
</html>